name: flutter_better_pickers
description: "This is a multi-picker package that includes several different modes, making it easy to use."
version: 0.0.8
homepage: "https://github.com/SwanFlutter/flutter_better_pickers"


platforms:
  android:
  ios:

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  media_manager: ^0.1.2
  external_path_ios_mac: ^0.0.7
  loading_animation_widget: ^1.3.0
  image_picker: ^1.2.1
  flutter_saver: ^0.0.6
  camera: ^0.11.3
  permission_handler: ^12.0.1
  path: ^1.9.1
  lucide_icons_flutter: ^3.1.8
  native_android_path: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
